# FOSUser bundle confguration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: no-reply@tml4you.com
        sender_name: No-Reply