<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\Blog;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function update(Blog $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    public function remove(Blog $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
