<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\BlogContact;

/**
 * BlogContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function update(BlogContact $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    public function remove(BlogContact $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
