<?php

namespace AppBundle\Entity\Repositories;

use AppBundle\Entity\Comember;

/**
 * Comember
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComemberRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Comember $entity
     */
    public function update(Comember $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    /**
     * @param Comember $entity
     */
    public function remove(Comember $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}