<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function update(Comment $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    public function remove(Comment $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
