<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\Configuration;
use Doctrine\ORM\QueryBuilder;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
    public function update(Configuration $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    /**
     * @param int $start
     * @param int $limit
     * @param array $order
     * @param string $filter
     * @return array
     */
    public function datableElement($start = 0, $limit = 10, $order = array(), $filter ='')
    {
        $query = $this->createQueryBuilder('configuration');
        $query->setFirstResult($start);
        $query->setMaxResults($limit);
        if(!empty($order)) {
            switch($order['column']) {
                case 1:
                    $query->addOrderBy('configuration.description',$order['dir']);
                    break;
                case 2:
                    $query->addOrderBy('configuration.value',$order['dir']);
                    break;
                default:
                    $query->addOrderBy('configuration.field',$order['dir']);
            }
        }

        if(!empty($filter)) {
            $query = $this->addQueryFilter($query, $filter);
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @return mixed
     */
    public function getCountTotal()
    {
        $query = $this->createQueryBuilder('configuration');
        $query->select($query->expr()->count('configuration.id'));

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @param $filter
     * @return mixed
     */
    public function getFilterTotal($filter)
    {
        $query = $this->createQueryBuilder('configuration');
        $query->select($query->expr()->count('configuration.id'));
        if(!empty($filter)) {
            $query = $this->addQueryFilter($query, $filter);
        }

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @param QueryBuilder $query
     * @param $filter
     * @return QueryBuilder
     */
    private function addQueryFilter(QueryBuilder $query, $filter)
    {
        $expr = $query->expr();
        $query->orWhere($expr->like('configuration.field',':filter_str'));
        $query->orWhere($expr->like('configuration.description',':filter_str'));
        $query->orWhere($expr->like('configuration.value',':filter_str'));
        $query->setParameter('filter_str', '%'.$filter.'%');
        return $query;
    }

}
