<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\GuestCode;
use AppBundle\Entity\Profile;

/**
 * GuestCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestCodeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param GuestCode $entity
     */
    public function update(GuestCode $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    /**
     * @param GuestCode $entity
     */
    public function remove(GuestCode $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }

    /**
     * @param $code
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findValidCode($code) {
        $query = $this->createQueryBuilder('guest_code');
        $query
            ->where($query->expr()->eq('guest_code.code',':code'))
            ->andWhere($query->expr()->eq('guest_code.active',':active'))
            ->setMaxResults(1)
            ->setParameter('code', $code)
            ->setParameter('active',true)
        ;

        return $query->getQuery()->getOneOrNullResult();
    }

    /**
     * @param int $user
     */
    public function clearAllByUser($user) {
        $query = $this->createQueryBuilder('guest_code');
        $query
            ->delete()
            ->where($query->expr()->eq('guest_code.user',':user'))
            ->setParameter('user', $user)
        ;
        $query->getQuery()->execute();
    }
}
