<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\Log;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Log $entity
     */
    public function update(Log $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    /**
     * @param Log $entity
     */
    public function remove(Log $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }

    /**
     * @param $limit
     * @return array
     */
    public function getLatestLog($limit) {
        $query = $this->createQueryBuilder('log');
        $query
            ->setMaxResults($limit)
            ->orderBy($query->expr()->desc('log.created'))
        ;
        return $query->getQuery()->getResult();
    }
}
