<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\News;
use Doctrine\ORM\QueryBuilder;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param News $entity
     */
    public function update(News $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    /**
     * @param News $entity
     */
    public function remove(News $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }

    /**
     * @param int $start
     * @param int $limit
     * @param array $order
     * @param string $filter
     * @return array
     */
    public function datableElement($start = 0, $limit = 10, $order = array(), $filter ='')
    {
        $query = $this->createQueryBuilder('news');
        $query->setFirstResult($start);
        $query->setMaxResults($limit);
        if(!empty($order)) {
            switch($order['column']) {
                case 2:
                    $query->addOrderBy('news.created',$order['dir']);
                    break;
                default:
                    $query->addOrderBy('news.title',$order['dir']);
            }
        }

        if(!empty($filter)) {
            $query = $this->addQueryFilter($query, $filter);
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @return mixed
     */
    public function getCountTotal()
    {
        $query = $this->createQueryBuilder('news');
        $query->select($query->expr()->count('news.id'));

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @param $filter
     * @return mixed
     */
    public function getFilterTotal($filter)
    {
        $query = $this->createQueryBuilder('news');
        $query->select($query->expr()->count('news.id'));
        if(!empty($filter)) {
            $query = $this->addQueryFilter($query, $filter);
        }

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @param QueryBuilder $query
     * @param $filter
     * @return QueryBuilder
     */
    private function addQueryFilter(QueryBuilder $query, $filter)
    {
        $expr = $query->expr();
        $query->orWhere($expr->like('news.title',':filter_str'));
        $query->setParameter('filter_str', '%'.$filter.'%');
        return $query;
    }

    /**
     * @param int $limit
     * @return array
     */
    public function getLatestNews($limit = 10) {
        $query = $this->createQueryBuilder('news');
        $query->setMaxResults($limit);
        $query->orderBy($query->expr()->desc('news.created'));

        return $query->getQuery()->getResult();
    }
}
