<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\NewsCategory;
use Doctrine\ORM\QueryBuilder;

/**
 * NewsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param NewsCategory $entity
     */
    public function update(NewsCategory $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    /**
     * @param NewsCategory $entity
     */
    public function remove(NewsCategory $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }

    /**
     * @param int $start
     * @param int $limit
     * @param array $order
     * @param string $filter
     * @return array
     */
    public function datableElement($start = 0, $limit = 10, $order = array(), $filter ='')
    {
        $query = $this->createQueryBuilder('news_category');
        $query->setFirstResult($start);
        $query->setMaxResults($limit);
        if(!empty($order)) {
            /*switch($order['column']) {
                case 1:
                    $query->addOrderBy('post.title',$order['dir']);
                    break;
                default:
                    $query->addOrderBy('post.created',$order['dir']);
            }*/
        }

        if(!empty($filter)) {
            $query = $this->addQueryFilter($query, $filter);
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @return mixed
     */
    public function getCountTotal()
    {
        $query = $this->createQueryBuilder('news_category');
        $query->select($query->expr()->count('news_category.id'));

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @param $filter
     * @return mixed
     */
    public function getFilterTotal($filter)
    {
        $query = $this->createQueryBuilder('news_category');
        $query->select($query->expr()->count('news_category.id'));
        if(!empty($filter)) {
            $query = $this->addQueryFilter($query, $filter);
        }

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @param QueryBuilder $query
     * @param $filter
     * @return QueryBuilder
     */
    private function addQueryFilter(QueryBuilder $query, $filter)
    {
        $expr = $query->expr();
        $query->orWhere($expr->like('news_category.category',':filter_str'));
        $query->setParameter('filter_str', '%'.$filter.'%');
        return $query;
    }
}
