<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\PostComment;
use Doctrine\ORM\QueryBuilder;

/**
 * PostCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param PostComment $entity
     */
    public function update(PostComment $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    /**
     * @param PostComment $entity
     */
    public function remove(PostComment $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }

    /**
     * @param int $post
     * @param int $start
     * @param int $limit
     * @param array $order
     * @param string $filter
     * @return array
     */
    public function datableElement($post, $start = 0, $limit = 10, $order = array(), $filter ='')
    {
        $query = $this->createQueryBuilder('post_comment');
        $query->innerJoin('post_comment.post','post');
        $query->setFirstResult($start);
        $query->setMaxResults($limit);
        $query->where($query->expr()->eq('post.id',':post'));
        $query->setParameter('post', $post);
        if(!empty($order)) {
            switch($order['column']) {
                case 1:
                    $query->addOrderBy('post_comment.title',$order['dir']);
                    break;
                case 2:
                    $query->addOrderBy('post_comment.created',$order['dir']);
                    break;
                default:
                    $query->addOrderBy('post_comment.name',$order['dir']);
            }
        }

        if(!empty($filter)) {
            $query = $this->addQueryFilter($query, $filter);
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @param $post
     * @return mixed
     */
    public function getCountTotal($post)
    {
        $query = $this->createQueryBuilder('post_comment');
        $query->innerJoin('post_comment.post','post');
        $query->where($query->expr()->eq('post.id',':post'));
        $query->setParameter('post', $post);
        $query->select($query->expr()->count('post_comment.id'));

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @param $post
     * @param $filter
     * @return mixed
     */
    public function getFilterTotal($post, $filter)
    {
        $query = $this->createQueryBuilder('post_comment');
        $query->innerJoin('post_comment.post','post');
        $query->where($query->expr()->eq('post.id',':post'));
        $query->setParameter('post', $post);
        $query->select($query->expr()->count('post_comment.id'));
        if(!empty($filter)) {
            $query = $this->addQueryFilter($query, $filter);
        }

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @param QueryBuilder $query
     * @param $filter
     * @return QueryBuilder
     */
    private function addQueryFilter(QueryBuilder $query, $filter)
    {
        $expr = $query->expr();
        $query->orWhere($expr->like('post_comment.title',':filter_str'));
        $query->orWhere($expr->like('post_comment.name',':filter_str'));
        $query->orWhere($expr->like('post_comment.created',':filter_str'));
        $query->setParameter('filter_str', '%'.$filter.'%');
        return $query;
    }
}
