<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function update(Post $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    public function remove(Post $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
