<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\Post;
use Doctrine\ORM\QueryBuilder;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Post $entity
     */
    public function update(Post $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    /**
     * @param Post $entity
     */
    public function remove(Post $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }

    /**
     * @param int $blog
     * @param int $start
     * @param int $limit
     * @param array $order
     * @param string $filter
     * @return array
     */
    public function datableElement($blog, $start = 0, $limit = 10, $order = array(), $filter ='')
    {
        $query = $this->createQueryBuilder('post');
        $query->innerJoin('post.blog','blog');
        $query->setFirstResult($start);
        $query->setMaxResults($limit);
        $query->where($query->expr()->eq('blog.id',':blog'));
        $query->setParameter('blog', $blog);
        if(!empty($order)) {
            switch($order['column']) {
                case 1:
                    $query->addOrderBy('post.title',$order['dir']);
                    break;
                default:
                    $query->addOrderBy('post.created',$order['dir']);
            }
        }

        if(!empty($filter)) {
            $query = $this->addQueryFilter($query, $filter);
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @param $blog
     * @return mixed
     */
    public function getCountTotal($blog)
    {
        $query = $this->createQueryBuilder('post');
        $query->innerJoin('post.blog','blog');
        $query->where($query->expr()->eq('blog.id',':blog'));
        $query->setParameter('blog', $blog);
        $query->select($query->expr()->count('post.id'));

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @param $blog
     * @param $filter
     * @return mixed
     */
    public function getFilterTotal($blog, $filter)
    {
        $query = $this->createQueryBuilder('post');
        $query->innerJoin('post.blog','blog');
        $query->where($query->expr()->eq('blog.id',':blog'));
        $query->setParameter('blog', $blog);
        $query->select($query->expr()->count('post.id'));
        if(!empty($filter)) {
            $query = $this->addQueryFilter($query, $filter);
        }

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @param QueryBuilder $query
     * @param $filter
     * @return QueryBuilder
     */
    private function addQueryFilter(QueryBuilder $query, $filter)
    {
        $expr = $query->expr();
        $query->andWhere($expr->orX(
            $expr->like('post.title',':filter_str'),
            $expr->like('post.created',':filter_str')
        ));
        $query->setParameter('filter_str', '%'.$filter.'%');
        return $query;
    }
}
