<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\Profile;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends \Doctrine\ORM\EntityRepository
{
    public function update(Profile $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    public function remove(Profile $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
