<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\ProfileMessage;

/**
 * ProfileMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileMessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function update(ProfileMessage $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    public function remove(ProfileMessage $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
