<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\SocialMessage;

/**
 * SocialMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialMessageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param SocialMessage $entity
     */
    public function update(SocialMessage $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    /**
     * @param SocialMessage $entity
     */
    public function remove(SocialMessage $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }

    /**
     * @param int $limit
     * @return array
     */
    public function getLatest($limit = 10) {
        $query = $this->createQueryBuilder('social_message');
        $query
            ->setMaxResults($limit)
            ->orderBy($query->expr()->desc('social_message.updated'));

        return $query->getQuery()->getResult();
    }
}
