<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\TestCourses;

/**
 * TestCourses
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestCoursesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param TestCourses $entity
     */
    public function update(TestCourses $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    /**
     * @param TestCourses $entity
     */
    public function remove(TestCourses $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }

    /**
     * @param $userId
     * @return array
     */
    public function getUserCourses($userId) {
        $query = $this->createQueryBuilder('test_courses');
        $query
            ->where($query->expr()->eq('test_courses.user',':user'))
            ->orderBy($query->expr()->asc('test_courses.level'))
            ->setParameter('user', $userId)
        ;
        return $query->getQuery()->getResult();
    }
}