<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\Transfer;

/**
 * TransferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferRepository extends \Doctrine\ORM\EntityRepository
{
    public function update(Transfer $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    public function remove(Transfer $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
